### ISSUE TITLE
Add examples

### ISSUE THREAD

**Issue by andeplane** [ComputationalPhysics/atomify-lammps#140]
When you open atomify, there should be some examples so users can start right away.
# TODO:
- [x] Design file format
- [ ] Create server software / update server database

# Client
- [x] Design example page
- [x] Communicate with server
- [x] Copy all examples to writable path so we can run and edit examples
- [x] Choose LJ as initial simulation
- [ ] Add edit button to examples (so when you hover you have both play and edit)
- [ ] Fix so play doesn't open script in editor unless 1) edit is pressed or 2) play is pressed and edit menu button is pressed

# Examples
- [x] Diffusion examples
- [ ] Viscosity examples?
- [ ] Other examples demonstrating atomify features (per atom coloring etc)

**Comment by andeplane** [comment]
We have added an examples-tab in the right sidebar. We should include a huge list here showing both LAMMPS and Atomify features.

**Comment by dragly** [comment]
Add 3-5 examples to QRC. These will be copied to .local/atomify or .config/atomify upon app start if they don't exist (add button to purge examples to editor). In the long run, notify user if examples are updated in new version. In the future, community simulations can be downloaded to the same folder.

**Comment by andeplane** [comment]
The examples should work as a simplified tutorial to LAMMPS and Atomify. This means that they should be filled with comments.
